name: estore
description: "E Store for you"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  http: ^1.2.2
  get_it: ^8.0.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  toastification: ^2.3.0
  sqflite: ^2.4.0
  connectivity_plus: ^6.1.0
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  mockito: ^5.4.4

flutter:

  uses-material-design: true
  assets:
    - assets/images/